name: Tests

on:
  push:
    branches: [main]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Run checks
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17
      - name: Compile project
        run: |
          chmod +x gradlew
          ./gradlew jar
      - name: Run checks
        run: |
          ./gradlew check